/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_rocketmq_remoting_protocol_RemotingCommandCodec */

#ifndef _Included_org_apache_rocketmq_remoting_protocol_RemotingCommandCodec
#define _Included_org_apache_rocketmq_remoting_protocol_RemotingCommandCodec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_rocketmq_remoting_protocol_RemotingCommandCodec
 * Method:    decodeRemotingCommand
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_org_apache_rocketmq_remoting_protocol_RemotingCommandCodec_decodeRemotingCommand
  (JNIEnv *, jclass, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
