/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_rocketmq_store_util_ARMUtils */

#ifndef _Included_org_apache_rocketmq_store_util_ARMUtils
#define _Included_org_apache_rocketmq_store_util_ARMUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_rocketmq_store_util_ARMUtils
 * Method:    encode
 * Signature: ([BJIIIIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_rocketmq_store_util_ARMUtils_encode
  (JNIEnv *, jclass, jbyteArray, jlong, jint, jint, jint, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
