/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_rocketmq_common_utils_ARMSpinLock */

#ifndef _Included_org_apache_rocketmq_common_utils_ARMSpinLock
#define _Included_org_apache_rocketmq_common_utils_ARMSpinLock
#ifdef __cplusplus
extern "C" {
#endif
#undef org_apache_rocketmq_common_utils_ARMSpinLock_memBlockSize
#define org_apache_rocketmq_common_utils_ARMSpinLock_memBlockSize 1048576L
#undef org_apache_rocketmq_common_utils_ARMSpinLock_cacheLineSize
#define org_apache_rocketmq_common_utils_ARMSpinLock_cacheLineSize 64L
/*
 * Class:     org_apache_rocketmq_common_utils_ARMSpinLock
 * Method:    lock
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_apache_rocketmq_common_utils_ARMSpinLock_lock
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_apache_rocketmq_common_utils_ARMSpinLock
 * Method:    unlock
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_apache_rocketmq_common_utils_ARMSpinLock_unlock
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
